name: OS Support Smoke Test

on:
  push:
    branches: [ main, staging, trying ]
  pull_request:
    branches: [ main ]

env:
  JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1

jobs:
  smoke-test:
    # This name is hard-referenced from bors.toml
    # Remember to update that if this name, or the matrix.os changes
    name: Run smoke tests on ${{ matrix.os }}
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-2022, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Clear broken cache parts (windows)
        if: matrix.os == 'windows-2022'
        uses: JesseTG/rm@v1.0.2
        with:
          path: C:\Users\runneradmin\.m2\repository\org\agrona\agrona
      - name: Clear broken cache parts (windows)
        if: matrix.os == 'windows-2022'
        uses: JesseTG/rm@v1.0.2
        with:
          path: C:\Users\runneradmin\.m2\repository\uk\co\real-logic\sbe-tool
      - name: Clear broken cache parts (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        uses: JesseTG/rm@v1.0.2
        with:
          path: /home/runner/.m2/repository/org/agrona/agrona
      - name: Clear broken cache parts (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        uses: JesseTG/rm@v1.0.2
        with:
          path: /home/runner/.m2/repository/uk/co/real-logic/sbe-tool
      - name: Clear broken cache parts (macos)
        if: matrix.os == 'macos-latest'
        uses: JesseTG/rm@v1.0.2
        with:
          path: /Users/runner/.m2/repository/org/agrona/agrona
      - name: Clear broken cache parts (macos)
        if: matrix.os == 'macos-latest'
        uses: JesseTG/rm@v1.0.2
        with:
          path: /Users/runner/.m2/repository/uk/co/real-logic/sbe-tool
      - name: Build relevant modules
        run: mvn -B -am -pl qa/integration-tests install -DskipTests -DskipChecks "-Dmaven.javadoc.skip=true" -T1C
      - name: Run smoke test
        run: mvn -B -pl qa/integration-tests verify -P smoke-test -DskipUTs -DskipChecks
